on:
  push:
    branches:
      - test
      - prod
      - dev

name: iOS-ipa-build

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release

      # Create the .ipa file
      - name: Create .ipa file
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/iphoneos/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist \
            -allowProvisioningUpdates

      # Upload the .ipa file to the release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKENN }}
          file: build/ios/ipa/Runner.ipa
          tag: v1.2
