on:
  push:
    branches:
      - test
      - prod
      - dev

name: iOS-ipa-build

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKENN }}
          file: build/ios/iphoneos/Runner.app
          tag: v1.1
          overwrite: false
          body: "This is the first release"
