name: Build iOS and Android IPA/APK
on:
  push:
    branches:
      - test

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Clean
        run: flutter clean
      - name: Get dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: iOS-Build
          path: build/ios/iphoneos/app.ipa

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Clean
        run: flutter clean
      - name: Get dependencies
        run: flutter pub get
      - name: Build Android APK for test branch
        run: flutter build apk --release -t lib/main_dev.dart --flavor dev
      - name: Upload test apk APK
        uses: actions/upload-artifact@v3
        with:
          name: Android-Build
          path: build/app/outputs/flutter-apk/app-test-release.apk
